[package]
name = "protocol-anthropic-messages"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bytes.workspace = true
protocol-openai-chat-completions = { path = "../protocol-openai-chat-completions" }
provider-x-core = { path = "../provider-x-core" }
provider-x-protocol = { path = "../provider-x-protocol" }
serde_json.workspace = true
thiserror.workspace = true

[lints]
workspace = true
